### ISSUE TITLE
Private groups created don't show up in myGroups

### ISSUE THREAD

**Issue by jiaweizhang** [jiaweizhang/Rowcord#9]

**Comment by alanguo5520** [comment]
might be a backend problem? api call doesn't tell me about public/private for my groups

**Comment by jiaweizhang** [comment]
Will add the pub/private field to json response

**Comment by jiaweizhang** [comment]
https://github.com/jiaweizhang/Rowcord/issues/24

**Comment by alanguo5520** [comment]
Fixed.
